name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-editorconfig-checker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.1"
      - uses: "editorconfig-checker/action-editorconfig-checker@main"
      - run: "editorconfig-checker"

  ci:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        task: [Ludwig_Theo_Tp0, Ludwig_Theo_Tp1, Ludwig_Theo_Tp2]

    steps:
      - uses: "actions/checkout@v4.2.1"

      - uses: "actions/setup-dotnet@v4.0.1"
        with:
          dotnet-version: "8.0.x"

      - run: "dotnet restore"
        working-directory: ${{ matrix.task }}

      - run: "dotnet format --verify-no-changes --verbosity diagnostic"
        working-directory: ${{ matrix.task }}
